[target.x86_64-linux-android]
linker = "/home/jacky/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android31-clang"

[target.aarch64-linux-android]
linker = "/home/jacky/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android31-clang"

[env]
# must specify due to ring: https://github.com/briansmith/ring/blob/main/BUILDING.md#cross-compiling
"CC_x86_64-linux-android" = "/home/jacky/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android31-clang"
# # must specify due to ring: https://github.com/briansmith/ring/blob/main/BUILDING.md#cross-compiling
"AR_x86_64_linux_android" = "/home/jacky/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar"
