[target.x86_64-linux-android]
linker = "/home/jacky/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android31-clang"

[target.aarch64-linux-android]
linker = "/home/jacky/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android31-clang"
