[package]
name = "nym-jni"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jni = "0.20.0"
sphinx = { git = "https://github.com/nymtech/nym", rev = "b7aa84cd5a5589b4921feb6a4633a4a2de530d14" }

[lib]
crate_type = ["cdylib"]
