[package]
name = "nym-jni"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jni = "0.20.0"
nym-client = { git = "https://github.com/nymtech/nym", rev = "b7aa84c" }

[lib]
crate_type = ["cdylib"]
